### ISSUE TITLE
base64 -w0 is not a valid option on mac.

### ISSUE THREAD

**Issue by beemarie** [IBM/knative101#28]

**Comment by beemarie** [comment]
@duglin are you running linux?  Does -b 0 work instead?

**Comment by duglin** [comment]
hmmm no `-b` on Ubuntu  :-(
We may need to mention both options.  Will tweak it in a bit...

**Comment by beemarie** [comment]
Reminder that there was an update to the comments in the `docker-secret.yaml` file too that should be addressed. We can always just remove the comment.
