### ISSUE TITLE
issue with knctl install instruction

### ISSUE THREAD

**Issue by guyos** [IBM/knative101#53]
In exercise-0 instructions on how to install knctl, the algorithm number for SHA checksum seems to be wrong. '265' instead of '256'
Usage: shasum [OPTION]... [FILE]...
Print or check SHA checksums.
With no FILE, or when FILE is -, read standard input.

  -a, --algorithm   1 (default), 224, 256, 384, 512, 512224, 512256

**Comment by duglin** [comment]
thanks!  #54 fixes this
