### ISSUE TITLE
Exericise 6:  New revision not active

### ISSUE THREAD

**Issue by robomeister** [IBM/knative101#58]
Hi there.  Going through the exercises.  On exercise 6, when I run the service.yaml file, the build works, but the new revision does not fire up.  If I try to just deploy the new service, the new revision does not fire up either.  Here's the results of the 'knctl revisions list':

Revisions

Service        Name                 Tags  Annotations  Conditions  Age  Traffic
fib-knative    fib-knative-00003    -     -            1 OK / 4    8m   -
~              fib-knative-00002    -     -            1 OK / 4    19m  -
~              fib-knative-00001    -     -            4 OK / 5    40m  100% -> fib-knative.default.roborail.tor01.containers.appdomain.cloud

**Comment by robomeister** [comment]
When I tried to switch the route manually, I got this:

[root@jumpserver fib-knative]# knctl rollout --route fib-knative -p fib-knative:latest=50% -p fib-knative:previous=50%
Error: Expected to find revision with tag 'latest' for service 'fib-knative'

**Comment by robomeister** [comment]
I skipped ahead to exercise 7, and the build did not become ready:

knctl deploy --service fib-knative --git-url https://github.com/IBM/fib-knative --git-revision vnext --service-account build-bot --image us.icr.io/robobob/fib-knative:vnext --managed-route=false
Name  fib-knative

Waiting for new revision (after revision 'fib-knative-00003') to be created...

Tagging new revision 'fib-knative-00004' as 'latest'

Tagging older revision 'fib-knative-00003' as 'previous'

Annotating new revision 'fib-knative-00004'

Watching build logs...

build-step-credential-initializer | {"level":"info","ts":1552260015.8214812,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized.","commit":"695fd25"}
build-step-git-source-0 | {"level":"info","ts":1552260018.9826236,"logger":"fallback-logger","caller":"git-init/main.go:92","msg":"Successfully cloned \"https://github.com/IBM/fib-knative\" @ \"vnext\" in path \"/workspace\"","commit":"695fd25"}
build-step-build-and-push | INFO[0000] Downloading base image node:alpine
build-step-build-and-push | 2019/03/10 23:20:22 No matching credentials were found, falling back on anonymous
build-step-build-and-push | INFO[0001] Unpacking rootfs as cmd RUN npm install --only=production requires it.
build-step-build-and-push | INFO[0004] Taking snapshot of full filesystem...
build-step-build-and-push | INFO[0004] Skipping paths under /kaniko, as it is a whitelisted directory
build-step-build-and-push | INFO[0004] Skipping paths under /sys, as it is a whitelisted directory
build-step-build-and-push | INFO[0004] Skipping paths under /dev, as it is a whitelisted directory
build-step-build-and-push | INFO[0004] Skipping paths under /builder/home, as it is a whitelisted directory
build-step-build-and-push | INFO[0004] Skipping paths under /var/run, as it is a whitelisted directory
build-step-build-and-push | INFO[0004] Skipping paths under /proc, as it is a whitelisted directory
build-step-build-and-push | INFO[0004] Skipping paths under /workspace, as it is a whitelisted directory
build-step-build-and-push | INFO[0006] WORKDIR /usr/src/app
build-step-build-and-push | INFO[0006] cmd: workdir
build-step-build-and-push | INFO[0006] Changed working directory to /usr/src/app
build-step-build-and-push | INFO[0006] Creating directory /usr/src/app
build-step-build-and-push | INFO[0006] Taking snapshot of files...
build-step-build-and-push | INFO[0006] Using files from context: [/workspace/package.json]
build-step-build-and-push | INFO[0006] COPY package*.json ./
build-step-build-and-push | INFO[0006] Taking snapshot of files...
build-step-build-and-push | INFO[0006] RUN npm install --only=production
build-step-build-and-push | INFO[0006] cmd: /bin/sh
build-step-build-and-push | INFO[0006] args: [-c npm install --only=production]
build-step-build-and-push | npm notice created a lockfile as package-lock.json. You should commit this file.
build-step-build-and-push | npm WARN fib-knative@1.0.0 No description
build-step-build-and-push | npm WARN fib-knative@1.0.0 No repository field.
build-step-build-and-push |
build-step-build-and-push | added 48 packages from 36 contributors and audited 121 packages in 2.066s
build-step-build-and-push | found 0 vulnerabilities
build-step-build-and-push |
build-step-build-and-push | INFO[0008] Taking snapshot of full filesystem...
build-step-build-and-push | INFO[0009] Skipping paths under /kaniko, as it is a whitelisted directory
build-step-build-and-push | INFO[0009] Skipping paths under /sys, as it is a whitelisted directory
build-step-build-and-push | INFO[0009] Skipping paths under /dev, as it is a whitelisted directory
build-step-build-and-push | INFO[0009] Skipping paths under /builder/home, as it is a whitelisted directory
build-step-build-and-push | INFO[0009] Skipping paths under /var/run, as it is a whitelisted directory
build-step-build-and-push | INFO[0009] Skipping paths under /proc, as it is a whitelisted directory
build-step-build-and-push | INFO[0009] Skipping paths under /workspace, as it is a whitelisted directory
build-step-build-and-push | INFO[0010] Using files from context: [/workspace/server.js /workspace/fibUtils.js]
build-step-build-and-push | INFO[0010] COPY server.js fibUtils.js ./
build-step-build-and-push | INFO[0010] Taking snapshot of files...
build-step-build-and-push | INFO[0010] EXPOSE 8080
build-step-build-and-push | INFO[0010] cmd: EXPOSE
build-step-build-and-push | INFO[0010] Adding exposed port: 8080/tcp
build-step-build-and-push | INFO[0010] CMD [ "npm", "start" ]
build-step-build-and-push | 2019/03/10 23:20:33 existing blob: sha256:8e402f1a9c577ded051c1ef10e9fe4492890459522089959988a4852dee8ab2c
build-step-build-and-push | 2019/03/10 23:20:33 existing blob: sha256:5e2195587d10f216b17e3afe1d4bce65fffd0bf7b17e64787924cb9b3855e8a7
build-step-build-and-push | 2019/03/10 23:20:33 existing blob: sha256:6f595b2fc66d59048a67a618ee4ea0d5faa657ad6db556eb3441ffa1843dcd4c
build-step-build-and-push | 2019/03/10 23:20:34 pushed blob sha256:8a597036058da374f08e90b5e0d53d1ecdf037603b0311f0b49c61f00ccaaef3
build-step-build-and-push | 2019/03/10 23:20:34 pushed blob sha256:875b383f735d8a91b7e7c8428cfc3f6cda22064fda6db0e60d61c8fe0f1fd906
build-step-build-and-push | 2019/03/10 23:20:34 pushed blob sha256:9c30a8ae76d50ae3e209582bb74b85d07932303cd0bcb675c95473488ff850a9
build-step-build-and-push | 2019/03/10 23:20:34 pushed blob sha256:e3f35b51885187ab47f0ae6960b8984c70f74e6480711565b054f54bda5c4b6c
build-step-build-and-push | 2019/03/10 23:20:35 pushed blob sha256:07fe6e0f7fb0f17b3737482f2e4aba91232d40f5dfeadfc91df098b1afe07eb3
build-step-build-and-push | 2019/03/10 23:20:35 us.icr.io/robobob/fib-knative:vnext: digest: sha256:de9da60a1d48d08a8faaa397d47ea509a2e0222a033dfc4564dc09ee6f56623d size: 1401
nop | Build successful

Waiting for new revision 'fib-knative-00004' to be ready for up to 5m0s (logs below)...

Revision 'fib-knative-00004' did not became ready

**Comment by robomeister** [comment]
Looks like it was my pull secret.  I switched to using the default-us-icr-io pull secret and all was well

**Comment by beemarie** [comment]
@robomeister glad to hear it! Thanks for following back up!

**Comment by robomeister** [comment]
Yeah, I just decoded the ibm-cr-secret I created and it turns out I double-pasted the registry token when creating the secret in the first place.  Big oops.
